services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  database:
    image: postgres:15
    restart: always
    container_name: elevateDatabase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: elevateDatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
