services:
  database:
    image: postgres:15
    container_name: elevate-database
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elevate_network

  backend:
    build:
      context: ./backend
    container_name: elevate-backend
    environment:
      - NODE_ENV=development
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"
    depends_on:
      - database
    volumes:
      - ./backend:/app
    networks:
      - elevate_network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    platform: linux/amd64
    container_name: elevate-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - elevate_network

volumes:
  postgres_data:

networks:
  elevate_network:
    driver: bridge
