services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=gym_tracking
    depends_on:
      - database
    volumes:
    - ./backend:/app
    - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database:
    image: postgres:15
    container_name: gym_tracking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gym_tracking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
